server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-authentication-service-public-routes
          uri: lb://user-authentication-service
          predicates:
            - Path=/api/v1/auth/**

        - id: product-service-public-routes
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**

        - id: user-authentication-service-user-protected-routes
          uri: lb://user-authentication-service
          predicates:
            - Path=/api/v1/users/**

        - id: product-service-admin-protected-routes
          uri: lb://product-service
          predicates:
            - Path=/api/v1/admin/products/**

        - id: user-authentication-service-admin-protected-routes
          uri: lb://user-authentication-service
          predicates:
            - Path=/api/v1/admin/users/**

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka
  instance:
    prefer-ip-address: true

application:
  security:
    jwt:
      secret-key: +Shd3xxA9idbJK1G1nfnoS5vgYOTGIqmlB21pTuFFPDynMwq8PWDC+kvRDt5b5YE
