server:
  port: 8081

spring:
  application:
    name: user-authentication-service
  profiles:
    active: local

application:
  security:
    jwt:
      expiration: 86400000 # 1 day in milliseconds
      refresh-token:
        expiration: 604800000 # 7 days in milliseconds